Lumberjack work update

diff --git a/lumberjack/hpc/local_glidein b/lumberjack/hpc/local_glidein
--- a/lumberjack/hpc/local_glidein
+++ b/lumberjack/hpc/local_glidein
@@ -1,6 +1,13 @@
 #!/bin/bash
 
 # Terminal utils
+BL="\033[1;34m"
+YL="\033[1;33m"
+WHT="\033[1;97m"
+CY="\033[1;36m"
+MGT="\033[1;35m"
+GR="\033[1;32m"
+NO_COLOR="\033[0m"
 
 # Launch a full stack CMS glidein on a set of THETA nodes
 # Gathering parameters for the request
@@ -22,7 +29,7 @@ while getopts 'u:n:q:t:v:j:f:' flag; do
     f) SCHEDD_FILE="${OPTARG}" ;;
     a) ALLOCATION="${OPTARG}" ;;
     v) verbose='true' ;;
-    *) echo "Usage: $0 -u [<THETA user>] -n [<node cnt>] [<THETA base directory>]" 1>&2 ; exit 1
+    *) echo "Usage: $0 -u [<THETA user>] -n [<node cnt>] -q [<THETA queue>] -t [<Node time required>] -f [<SCHEDD exported job queue file location] -a [<THETA allocation]>" 1>&2 ; exit 1
        ;;
   esac
 done
@@ -31,7 +38,8 @@ SLOT_PREFIX="cobalt-cms-${JOB_ID}"
 GLIDEIN_NAME="cobalt-cms-${JOB_ID}@theta.alcf.anl.gov"
 THETA_BASE_DIR="/projects/${ALLOCATION}/job_area/${SLOT_PREFIX}"
 
-echo "====== Submitting a Lumberjack cobalt job from ${HOSTNAME} under local Linux user $(whoami)"
+echo "====== Submitting a Lumberjack cobalt job from ${HOSTNAME}"
+echo "Local Linux user: $(whoami)"
 LNS=$(qstat -u ${THETA_USER} | wc -l)
 if [ $LNS -gt 2 ]
 then
@@ -39,11 +47,13 @@ then
   qstat -u ${THETA_USER}
 fi
 
+echo ""
 echo ====== Creating base directory on shared storage
 mkdir ${THETA_BASE_DIR}
-echo INFO: Using directory $THETA_BASE_DIR
+echo Using directory $THETA_BASE_DIR
 
 # Set up local Condor installation
+echo ""
 echo ====== Writing base files
 echo Copy the "skeleton" folder as-is
 cp -dR skeleton/* $THETA_BASE_DIR/
@@ -62,6 +72,84 @@ COLLECTOR_NAME = coll_${GLIDEIN_NAME}
 SCHEDD_NAME = sched_${GLIDEIN_NAME}
 STARTD_NAME = startd_${GLIDEIN_NAME}
 EOF
+
+echo ""
+echo "====== Analyzing job_queue.log for directories needed by my jobs"
+echo ""
+SANDBOX_DIR=${PWD}/${SLOT_PREFIX}/sandbox
+ORIG_SCHEDD_HOST=$(grep -wR 'GlobalJobId' job_queue.log | awk '{print $4}' | tr -d \" | awk -F# '{print $1}' | sort -u)
+echo -e "${YL}Input job_queue.log indicates my source Schedd host is: ${ORIG_SCHEDD_HOST}${NO_COLOR}"
+WORKDIR_LIST=$(grep -R Iwd job_queue.log | awk '{print $4}' | sort -u | tr -d \")
+
+echo -e "${MGT}"
+echo -e "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+echo -e "# Lumberjack does not yet support file transfer                          "
+echo -e "# Make sure the following files from the original Schedd are available to"
+echo -e "# this HPC-minicondor job by placing them into:                          "
+echo -e "# $SANDBOX_DIR"
+echo -e "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+echo -e ""
+echo -e "# Tips:"
+echo -e "# To pull the file list from the local(HPC) login node. First make sure that there is networking connectivity between the login node and the remote schedd via SSH (port 22). Files will be copied via 'scp', I have prepared the exact command recipe. If both networking and authentication via ssh are possible between the two machines, this script will **automatically** atemmpt to run the scp command and pull the necessary files."
+echo -e "scp root@${ORIG_SCHEDD_HOST}:'${FILE_LIST}' ${SANDBOX_DIR}"
+echo -e "# To push the files from the remote schedd machine. First make sure that there is networking connectivity between the login node and the remote schedd via SSH (port 22). If there is only one-way connectivity, as is the case of FNAL (our machines can not be accessed from offsite, and ANL is offsite but also DOE. Anyway, when this is the case, we can just login to the Schedd and scp the files over to the login node, which by default has ssh connectivity most of the time. The only caveat here is that we still need someone (Maria) to do this by hand with a token that lives in her phone. I have prepared that command if that is your case, please login to your Schedd machine ${SCHEDD_ORIG_HOST} and run the following: "
+echo -e "scp ${FILE_LIST} $(whoami)@theta.alcf.anl.gov:${SANDBOX_DIR}"
+
+# This for loop is not needed, we are assuming there's a single, common IWD for all exported jobs
+# But it might come helpful if we figure out how to do this cleanly
+for dir in $WORKDIR_LIST 
+do
+   echo "Original IWD: $dir"
+   ORIG_IWD=${dir}
+   NEWDIR="${PWD}/${SLOT_PREFIX}/sandbox"
+   mkdir -p $SANDBOX_DIR
+   echo "HPC-minicondor IWD: ${SANDBOX_DIR}"
+done
+
+# Create UserLog, Out and Err directories"
+OUT=$(grep -wR 'Out' job_queue.log | awk '{print $4}' | awk -F/ '{print $1}' | tr -d \" | sort -u)
+ERR=$(grep -wR 'Err' job_queue.log | awk '{print $4}' | awk -F/ '{print $1}' | tr -d \" | sort -u)
+LOG=$(grep -wR 'UserLog' job_queue.log | awk '{print $4}' | awk -F/ '{print $1}' | tr -d \" | sort -u)
+[ -z "$OUT" ] && echo "" || mkdir ${SANDBOX_DIR}/$OUT
+[ -z "$ERR" ] && echo "" || mkdir ${SANDBOX_DIR}/$ERR
+[ -z "$LOG" ] && echo "" || mkdir ${SANDBOX_DIR}/condor_log
+
+## Verify if we have a krb ticket, if so, attempt to SCP the files while we're at it
+# Files we will transfer/list: Cmd + TransferInput
+XFERS=$(grep -wR 'TransferInput' job_queue.log | awk '{print $4}' | sort -u | tr -d \")
+IFS=',' read -ra XFER_LIST <<< "$XFERS"
+
+ORIG_SCHEDD_CMD=$(grep -wR 'Cmd' job_queue.log | awk '{print $4}' | sort -u | tr -d \")
+ORIG_CMD=$(grep -wR 'Cmd' job_queue.log | awk '{print $4}' | sort -u | awk -F/ '{print $NF}' | tr -d \")
+FILE_LIST="${ORIG_SCHEDD_CMD}"
+#  echo -e "scp root@${ORIG_SCHEDD_HOST}:$ORIG_SCHEDD_CMD ${NEWDIR}/${ORIG_CMD}"
+for file in "${XFER_LIST[@]}"
+do
+    NEWLOC="${SANDBOX_DIR}/$file"
+    FILE_LIST="${FILE_LIST} ${ORIG_IWD}/$file"
+#    echo "scp root@${ORIG_SCHEDD_HOST}:${ORIG_IWD}/$file ${NEWLOC}"
+done
+kticket=`klist 2> /dev/null | grep FNAL.GOV`
+if [ -n "$kticket" ]; then
+  echo -e "${GR}Found a Kerberos ticket, I will attempt to copy files from ${ORIG_SCHEDD_HOST}"
+  echo -e "scp root@${ORIG_SCHEDD_HOST}:$ORIG_SCHEDD_CMD ${NEWDIR}/${ORIG_CMD}"
+  echo -e "scp root@${ORIG_SCHEDD_HOST}:'${FILE_LIST}' ${SANDBOX_DIR}"
+else
+    echo "No Kerberos ticket found! The following files are expected, please make sure they are present before the HPC job starts"
+    echo 'See "Useful commands:" above for clues'
+    echo "- ${SANDBOX_DIR}/${ORIG_CMD}"
+    for file in "${XFER_LIST[@]}"
+    do
+      NEWLOC="${SANDBOX_DIR}/$file"
+      echo "- $NEWLOC"
+    done
+fi
+echo ""
+echo -e "Done, verify that the file tree looks good"
+echo ""
+ls -ltrha ${SANDBOX_DIR}
+
+exit 0
 
 # write theta files
 echo ====== Writing files for job submission
@@ -100,5 +188,5 @@ echo INFO: Files written
 echo INFO: Submitting COBALT job 
 
 # Submit cobalt job
-cd ${THETA_BASE_DIR}; qsub -A ${ALLOCATION} -q ${QUEUE} -t ${TIME} -n ${NODE_CNT} --jobname=${SLOT_PREFIX} --attr ssds=required job.cobalt
+#cd ${THETA_BASE_DIR}; qsub -A ${ALLOCATION} -q ${QUEUE} -t ${TIME} -n ${NODE_CNT} --jobname=${SLOT_PREFIX} --attr ssds=required job.cobalt
 echo INFO: Done, check your job and files at ${THETA_BASE_DIR}
